import React from 'react';
import { Container, Typography, Box, Grid, Card, CardMedia } from '@mui/material';
import profilePicture from '../assets/profile_picture.jpg';

const Home = () => {
  return (
    <Container>
      <Box paddingTop={10} mt={4}>
        <Grid container spacing={4}>
          <Grid item xs={12} md={4}>
            <Card>
              <CardMedia
                component="img"
                height="auto"
                image={profilePicture}
                alt="Profile picture"
              />
            </Card>
          </Grid>
          <Grid item xs={12} md={8}>
            <Typography variant="body1">
              Welcome to my personal website! I'm a Ph.D. student at the University of South Carolina, specializing in artificial intelligence research. My work focuses on machine learning, natural language processing, and computer vision, and I am dedicated to developing innovative algorithms and techniques to advance the field of AI.
            </Typography>
            <Box mt={4}>
              <Typography variant="h4" gutterBottom>
                Research Interests
              </Typography>
              <Typography variant="body1">
                My primary research interests include:
              </Typography>
              <ul>
                <li>Deep learning for natural language understanding</li>
                <li>Reinforcement learning and optimization</li>
                <li>Generative models and unsupervised learning</li>
                <li>Transfer learning and domain adaptation</li>
              </ul>
            </Box>
            <Box mt={4}>
              <Typography variant="h4" gutterBottom>
                Recent Publications
              </Typography>
              <Typography variant="body1">
                {/* Add a list of your recent publications */}
                {/* Example: */}
                <ol>
                  <li>
                    <strong>Publication Title 1</strong>, Your Name, Co-Author(s) Name(s), Conference/Journal, Year.
                  </li>
                  <li>
                    <strong>Publication Title 2</strong>, Your Name, Co-Author(s) Name(s), Conference/Journal, Year.
                  </li>
                </ol>
              </Typography>
              <Typography variant="body1">
                NOTE: This page was generated by ChatGPT. I will update it later.
              </Typography>
            </Box>
          </Grid>
        </Grid>
      </Box>
    </Container>
  );
};

export default Home;
